djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
import learning.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learning.urls")),
]

learning/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static

from . import converters

from .views import curso_views
from .views import estudiante_views
from .views import inscripcion_views
from .views import login_views

register_converter(converters.DateRangeConverter, "daterange")


urlpatterns = [
    # Autenticación

    path("login/", login_views.CustomLoginView.as_view(), name='login'),
    path("logout/", login_views.logout_view, name="logout"),

    # Cursos
    path("cursos/", 
         curso_views.list_cursos,
         name="list_cursos"),
    path("cursos/<slug:slug>/",
         curso_views.detail_curso_slug,
         name="detail_curso_slug"),
    path("cursos/<int:curso_id>/",
         curso_views.detail_curso,
         name="detail_curso"),
    path("cursos/crear",
         curso_views.create_curso,
         name="create_curso"),
    path("cursos/actualizar/<int:curso_id>/",
         curso_views.update_curso,
         name="update_curso"),
    path("cursos/eliminar/<int:curso_id>/",
         curso_views.delete_curso,
         name="delete_curso"),
    path("cursos/ocultar/<int:curso_id>/",
         curso_views.hide_curso,
         name="hide_curso"),
    path("cursos/mostrar/<int:curso_id>/",
         curso_views.show_curso,
         name="show_curso"),
    path("cursos_eliminados/",
         curso_views.list_cursos_eliminados,
         name="list_cursos_eliminados"),
    # Estudiantes 
     path("estudiantes/",
         estudiante_views.list_estudiantes,
         name="list_estudiantes"),
     path("estudiantes/<int:estudiante_id>/",
         estudiante_views.detail_estudiante,
         name="detail_estudiante"),    
     path("estudiantes/crear/",
         estudiante_views.create_estudiante,
         name="create_estudiante"),
     path("estudiantes/actualizar/<int:estudiante_id>/",
         estudiante_views.update_estudiante,
         name="update_estudiante"),
    # Inscripciones
     path("inscripciones/",
         inscripcion_views.list_inscripciones,
         name="list_inscripciones"),
     path("inscripcion/",
         inscripcion_views.inscripcion,
         name="inscribir"),
     path("inscripcion-nombre/",
         inscripcion_views.inscripcion_por_nombre,
         name="inscribir-nombre"),
    # Informes inscripciones/estudiantes
     path(
        "estudiantes/<int:estudiante_id>/cursos/",
        curso_views.estudiante_cursos,
        name="estudiante_cursos",
    ),
     path(
        "cursos/<int:curso_id>/estudiantes/",
        curso_views.curso_estudiantes,
        name="curso_estudiantes",
    ),
     path(
        "cursos/<daterange:date_range>/",
        curso_views.cursos_por_fecha,
        name="cursos-por-fecha",
    )
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning/models/estudiante.py
from django.db import models
from .user import CustomUser

class Estudiante(models.Model):

    # Página 1: Información Básica
    usuario = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to="avatar", null=True, blank=True)
    dob = models.DateField(verbose_name="Fecha de Nacimiento")

    # Página 2: Información Educativa y de Intereses
    NIVEL_EDUCATIVO_CHOICES = [
        ('SEC', 'Secundaria'),
        ('PRE', 'Pregrado'),
        ('POS', 'Posgrado'),
        ('OTR', 'Otro')
    ]
    nivel_educativo = models.CharField(max_length=3, choices=NIVEL_EDUCATIVO_CHOICES, default='SEC', verbose_name="Nivel Educativo", null=True, blank=True)
    interest = models.TextField(verbose_name="Intereses", null=True, blank=True)
    habilidades = models.TextField(verbose_name="Habilidades", null=True, blank=True)

    # Página 3: Información Adicional
    bio = models.TextField(verbose_name="Biografía", null=True, blank=True)
    github = models.URLField(verbose_name="GitHub", max_length=200, null=True, blank=True)
    facebook = models.URLField(verbose_name="Facebook", max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} ({self.email})"

learning/models/instructor.py
from django.db import models
from .user import CustomUser

class Instructor(models.Model):
    usuario = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    bio = models.TextField()

    def __str__(self):
        return f"{self.nombre}"

learning/forms/inscripcion_form.py
from ..models import Inscripcion
from django import forms


class InscripcionForm(forms.ModelForm):

    class Meta:
        model = Inscripcion
        fields = ['estudiante', 'curso']
        labels = {
            'estudiante': 'Estudiante',
            'curso': 'Curso',
        }
        widgets = {
            'curso': forms.Select(attrs={'class': 'form-control'}),
            'estudiante': forms.Select(attrs={'class': 'form-control'}),
        }

learning/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, Http404
from .models import Curso, Estudiante, Inscripcion
from django.shortcuts import get_object_or_404
from .forms.estudiante_form import EstudianteForm, BusquedaEstudianteForm
from .forms.curso_form import CursoForm
from .forms.inscripcion_form import InscripcionForm

from django.contrib.auth import get_user_model, logout
from django.contrib.auth.views import LoginView
from .forms.login_form import CustomLoginForm
# Autenticación

class CustomLoginView(LoginView):
    template_name = "estudiante/estudiante_login.html"
    form_class = CustomLoginForm
    redirect_authenticated_user = True

def logout_view(request):
    logout(request)

    return redirect('list_estudiantes')

# Cursos

def list_cursos(request):
    """
    Listado de cursos no eliminados
    """
    cursos = Curso.objects.filter(is_deleted=False)

    busqueda = request.GET.get('search', '')

    if busqueda:
        cursos = Curso.objects.filter(descripcion__icontains=busqueda)

    context = {
        'cursos': cursos, 
        'titulo': 'Listado de Cursos',
        'busqueda': busqueda,
    }
    return render(request, "curso/cursos_list.html", context)

def detail_curso(request, curso_id):
    """
    Detalle de un curso
    """
    try:
        curso = Curso.objects.get(id=curso_id)
    except Curso.DoesNotExist:
        curso = None

    return render(request, 'curso/curso_detail.html', {'curso': curso})

def detail_curso_slug(request, slug):
    try:
        curso = Curso.objects.get(slug=slug)
    except Curso.DoesNotExist:
        curso = None

    return render(request, 'curso/curso_detail.html', {'curso': curso})

def create_curso(request):
    """
    Creación de un curso
    """
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_cursos")
    else:
        form = CursoForm()

    context = {
        'titulo': "Nuevo Curso",
        'form': form,
        'submit': 'Crear Curso'
    }
    return render(request, "curso/curso_form.html", context)

def update_curso(request, curso_id):
    """
    Actualización de un curso
    """
    curso = get_object_or_404(Curso, id=curso_id)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect("list_cursos")
    else:
        form = CursoForm(instance=curso)
    context = {
        'titulo': "Actualización de Curso",
        'form': form,
        'submit': 'Actualizar Curso'
    }
    return render(request, "curso/curso_form.html", context)

def delete_curso(request, curso_id):
    """
    Eliminación de un curso
    """
    curso = get_object_or_404(Curso, id=curso_id)
    curso.delete()
    return redirect("list_cursos")

def hide_curso(request, curso_id):
    """
    Ocultar un curso
    """
    curso = get_object_or_404(Curso, id=curso_id)
    curso.is_deleted = True
    curso.save()
    return redirect("list_cursos")

def show_curso(request, curso_id):
    """
    Restaurar un curso
    """
    curso = get_object_or_404(Curso, id=curso_id)
    curso.is_deleted = False
    curso.save()
    return redirect("list_cursos_eliminados")

def list_cursos_eliminados(request):
    """
    Listado de cursos eliminados
    """
    cursos = Curso.objects.filter(is_deleted=True)
    context = {'cursos': cursos, 'titulo': 'Listado de Cursos Eliminados'}
    return render(request, "curso/cursos_list_restore.html", context)

# Estudiantes

def list_estudiantes(request):
    estudiantes = Estudiante.objects.all()
    titulo = "Listado de Estudiantes"
    context = {'estudiantes': estudiantes, 'titulo': titulo}
    return render(request, "estudiante/estudiantes_list.html", context)

def detail_estudiante(request, estudiante_id):
    try:
        estudiante = Estudiante.objects.get(pk=estudiante_id)
        context = {'estudiante': estudiante}
        return render(request, 'estudiante/estudiante_detail.html', context)
    except Estudiante.DoesNotExist:
        return HttpResponse("Estudiante no encontrado", status=404)

def create_estudiante(request):
    if request.method == 'POST':
        form = EstudianteForm(request.POST, request.FILES)
        if form.is_valid():
            User = get_user_model()

            email = form.cleaned_data["email"]

            user = User.objects.create_user(username=email, email=email)
        
            nombre = form.cleaned_data['nombre']
            nombre_split = nombre.split(' ')
            user.first_name = nombre_split[0]
            user.last_name = nombre_split[-1]
            user.set_password('default')
            user.save()

            estudiante = form.save(commit=False)
            estudiante.usuario = user
            estudiante.save()
            return redirect("list_estudiantes")
    else:
        form = EstudianteForm()

    context = {
        'titulo': "Nuevo Estudiante",
        'form': form,
        'submit': 'Crear Estudiante'
    }
    return render(request, "estudiante/estudiante_form.html", context)

def update_estudiante(request, estudiante_id):
    """
    Actualización de un estudiante
    """
    estudiante = get_object_or_404(Estudiante, id=estudiante_id)
    if request.method == 'POST':
        form = EstudianteForm(request.POST, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect("list_estudiantes")
    else:
        form = EstudianteForm(instance=estudiante)
    context = {
        'titulo': "Actualización de Estudiante",
        'form': form,
        'submit': 'Actualizar Estudiante'
    }
    return render(request, "estudiante/estudiante_form.html", context)

# Inscripciones

def list_inscripciones(request):
    """
    Vista para listar todas las inscripciones
    """
    inscripciones = Inscripcion.objects.all().select_related("curso", "estudiante")
    titulo = "Listado de Inscripciones"
    context = {'inscripciones': inscripciones, 'titulo': titulo}
    return render(request, "inscripcion/inscripciones_list.html", context)

def inscripcion(request):
    """
    Vista para inscribir un estudiante a un curso
    """
    inscripcion_form = InscripcionForm()

    if request.method == 'POST':
        inscripcion_form = InscripcionForm(request.POST)
        if inscripcion_form.is_valid():
            inscripcion_form.save()
            return redirect('list_inscripciones')
    
    context = {
        'form': inscripcion_form,
    }
    return render(request, 'inscripcion/inscripcion_form.html', context)

def inscripcion_por_nombre(request):
    """
    Vista para inscribir un estudiante a un curso por su nombre
    """
    estudiantes = None
    inscripcion_form = InscripcionForm()
    inscripcion_form.fields['estudiante'].queryset = Estudiante.objects.none()

    if request.method == 'GET' and 'apellido' in request.GET:
        busqueda_form = BusquedaEstudianteForm(request.GET)
        if busqueda_form.is_valid():
            apellido = busqueda_form.cleaned_data['apellido']
            if apellido:
                estudiantes = Estudiante.objects.filter(nombre__icontains=apellido)
                inscripcion_form.fields['estudiante'].queryset = estudiantes
    else:
        busqueda_form = BusquedaEstudianteForm()
    
    if request.method == 'POST':
        inscripcion_form = InscripcionForm(request.POST)
        if inscripcion_form.is_valid():
            inscripcion_form.save()
            return redirect('list_inscripciones')
    
    context = {
        'busqueda_form' : busqueda_form,
        'inscripcion_form': inscripcion_form,
        'estudiantes': estudiantes,
    }
    return render(request, 'estudiante/inscripcion_form.html', context)

# Informes inscripciones/estudiantes

def estudiante_cursos(request, estudiante_id):
    """
    Vista para mostrar los cursos en los que está inscrito un estudiante en particular, incluyendo la fecha de inscripción
    """
    try:
        estudiante = Estudiante.objects.get(pk=estudiante_id)
        inscripciones = Inscripcion.objects.filter(
            estudiante=estudiante
        ).select_related("curso")
        titulo = f"Cursos de {estudiante.nombre}"

        context = {
            'estudiante': estudiante,
            'inscripciones': inscripciones,
            'titulo': titulo
        }
        return render(request, 'estudiante/estudiantes_cursos.html', context)
    except Estudiante.DoesNotExist:
        return HttpResponse("Estudiante no encontrado", status=404)

def curso_estudiantes(request, curso_id):
    """
    Vista para mostrar los estudiantes inscritos en un curso específico
    """
    try:
        curso = Curso.objects.get(pk=curso_id)
        inscripciones = Inscripcion.objects.filter(curso=curso).select_related(
            "estudiante"
        )
        titulo = f"Estudiantes inscritos en {curso.nombre}"

        context = {
            'curso': curso,
            'inscripciones': inscripciones,
            'titulo': titulo
        }
        return render(request, 'curso/cursos_estudiantes.html', context)
    except Curso.DoesNotExist:
        return HttpResponse("Curso no encontrado", status=404)   

def cursos_por_fecha(request, date_range):
    start_date, end_date = date_range
    cursos = Curso.objects.filter(
        fecha_publicacion__range=(start_date, end_date)
    ).order_by("fecha_publicacion")

    # Diccionario para traducir los nombres de los meses a español.
    mes_spanish = {
        "January": "Enero",
        "February": "Febrero",
        "March": "Marzo",
        "April": "Abril",
        "May": "Mayo",
        "June": "Junio",
        "July": "Julio",
        "August": "Agosto",
        "September": "Septiembre",
        "October": "Octubre",
        "November": "Noviembre",
        "December": "Diciembre",
    }

    cursos_por_mes = {}

    for curso in cursos:

learning/views/inscripcion_views.py
from django.shortcuts import render, redirect
from ..models import Inscripcion, Estudiante
from ..forms.estudiante_form import BusquedaEstudianteForm
from ..forms.inscripcion_form import InscripcionForm

def list_inscripciones(request):
    """
    Vista para listar todas las inscripciones
    """
    inscripciones = Inscripcion.objects.all().select_related("curso", "estudiante")
    titulo = "Listado de Inscripciones"
    context = {'inscripciones': inscripciones, 'titulo': titulo}
    return render(request, "inscripcion/inscripciones_list.html", context)

def inscripcion(request):
    """
    Vista para inscribir un estudiante a un curso
    """
    inscripcion_form = InscripcionForm()

    if request.method == 'POST':
        inscripcion_form = InscripcionForm(request.POST)
        if inscripcion_form.is_valid():
            inscripcion_form.save()
            return redirect('list_inscripciones')
    
    context = {
        'form': inscripcion_form,
    }
    return render(request, 'inscripcion/inscripcion_form.html', context)

def inscripcion_por_nombre(request):
    """
    Vista para inscribir un estudiante a un curso por su nombre
    """
    estudiantes = None
    inscripcion_form = InscripcionForm()
    inscripcion_form.fields['estudiante'].queryset = Estudiante.objects.none()

    if request.method == 'GET' and 'apellido' in request.GET:
        busqueda_form = BusquedaEstudianteForm(request.GET)
        if busqueda_form.is_valid():
            apellido = busqueda_form.cleaned_data['apellido']
            if apellido:
                estudiantes = Estudiante.objects.filter(nombre__icontains=apellido)
                inscripcion_form.fields['estudiante'].queryset = estudiantes
    else:
        busqueda_form = BusquedaEstudianteForm()
    
    if request.method == 'POST':
        inscripcion_form = InscripcionForm(request.POST)
        if inscripcion_form.is_valid():
            inscripcion_form.save()
            return redirect('list_inscripciones')
    
    context = {
        'busqueda_form' : busqueda_form,
        'inscripcion_form': inscripcion_form,
        'estudiantes': estudiantes,
    }
    return render(request, 'estudiante/inscripcion_form.html', context)

learning/views/login_views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from ..forms.login_form import CustomLoginForm
from django.shortcuts import redirect

class CustomLoginView(LoginView):
    template_name = "estudiante/estudiante_login.html"
    form_class = CustomLoginForm
    redirect_authenticated_user = True

def logout_view(request):
    logout(request)

    return redirect('list_estudiantes')

learning/templates/estudiante/estudiante_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'learning/css/style-student.css' %}"> <!-- Link to your external CSS file -->
{% endblock %}

{% block title %}{{ estudiante.nombre }}{% endblock %}

{% block content %}
    <div class="card container">
        <div class="header">
            <div class="header-content-top"></div>
            <div class="header-content-bottom animate-gradient">
                <div class="header-content">
                    <span class="avatar">
                        {% if estudiante.avatar %}
                            <img src="{{ estudiante.avatar.url }}" alt="Avatar" class="avatar-inner">
                        {% else %}
                            <span class="avatar-inner">{{ estudiante.nombre }}</span>
                        {% endif %}
                    </span>
                    <div class="info">
                        <div>
                            <h1 class="name">{{ estudiante.nombre }}</h1>
                            <p class="email">{{ estudiante.email }}</p>
                        </div>
                        <a href="{% url 'update_estudiante' estudiante.id %}" rel="nofollow">
                            <span title="Editar">
                                <i class="edit fa-regular fa-pen-to-square"></i>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid">
            <div class="item">
                <label class="label">Nacimiento</label>
                <p class="value">{{ estudiante.dob }}</p>
            </div>
            <div class="item">
                <label class="label">Biografía</label>
                {% if estudiante.bio %}
                    <p class="value">{{ estudiante.bio }}</p>
                {% else %}
                    <p class="value">Sin especificar</p>
                {% endif %}
            </div>
            <div class="item">
                <label class="label">Intereses</label>
                {% if estudiante.interest %}
                <p class="value">{{ estudiante.interest }}</p>
                {% else %}
                    <p class="value">Sin especificar</p>
                {% endif %}

            </div>
            <div class="item">
                <label class="label">Habilidades</label>
                {% if estudiante.habilidades %}
                <p class="value">{{ estudiante.habilidades }}</p>
                {% else %}
                    <p class="value">Sin especificar</p>
                {% endif %}
            </div>
            <div class="item">
                <label class="label">Redes sociales</label>
                <div class="social-buttons">
                    {% if estudiante.github %}
                        <a href="{{ estudiante.github }}" rel="nofollow" class="button">GitHub</a>
                    {% else %}
                        <p class="value">Sin especificar</p>
                    {% endif %}
                    {% if estudiante.facebook %}
                    <a href="{{ estudiante.facebook }}" rel="nofollow" class="button">Facebook</a>
                    {% else %}
                        <p class="value">Sin especificar</p>
                    {% endif %}
                </div>
            </div>
            <div class="item">
                <label class="label">Nivel Educativo</label>
                {% if estudiante.nivel_educativo %}
                    <p class="value">{{ estudiante.get_nivel_educativo_display }}</p>
                {% else %}
                    <p class="value">Sin especificar</p>
                {% endif %}
            </div>
        </div>
        <div class="d-grid gap-2 col-4 mx-auto">
            <a href="{% url 'list_estudiantes' %}" class="btn btn-primary mb-3 ms-4">Volver</a>
        </div>
    </div>
{% endblock %}

learning/templates/estudiante/estudiante_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container card card-body mx-auto px-40 my-5">
    <h1>{{ titulo }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if previous_step is not None %}
            <!-- Asegúrate de que la URL es correcta para "Paso Anterior" -->
            <a href="{% url 'create_estudiante' %}?prev_step={{ previous_step }}" class="btn btn-secondary">Paso Anterior</a>
        {% endif %}
        <button class="btn btn-primary" type="submit">{{ submit }}</button>
    </form>
</div>
{% endblock %}

learning/templates/estudiante/estudiante_login.html
{% extends 'base.html' %}

{% block content %}
<h1>Iniciar Sesión</h1>
<div class="container card card-body d-grid gap-2 col-4 mx-auto mt-5">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
    </form>
</div>
{% endblock %}

learning/templates/estudiante/estudiantes_cursos.html
{% extends 'base.html' %}

{% block title %}
    Listado de Cursos de {{ estudiante.nombre }}
{% endblock %}

{% block content %}
    <h1>{{ titulo }}</h1>
    <ul>
        {% for inscripcion in inscripciones %}
            <li>
                <div class="curso-nombre">{{ inscripcion.curso.nombre }}</div>
                <div class="fecha-inscripcion">Inscrito el {{ inscripcion.fecha_inscripcion|date:"d/m/Y" }}</div>
            </li>
        {% empty %}
            <li>No hay cursos inscritos</li>
        {% endfor %}
    </ul>
{% endblock %}

learning/templates/estudiante/estudiantes_list.html
{% extends 'base.html' %}

{% block title %}
    Listado de Estudiantes
{% endblock %}

{% block content %}
    <h1>{{ titulo }}</h1>
    <div>
        {% if user.is_authenticated %}
            <!-- Si el usuario ha iniciado sesión, muestra su nombre y el botón de cerrar sesión -->
            <span>Bienvenido, {{ user.get_full_name|default:user.email }}</span>
            <a href="{% url 'logout' %}" class="btn btn-secondary">Cerrar Sesión</a>
        {% else %}
            <!-- Si el usuario no ha iniciado sesión, muestra solo el botón de iniciar sesión -->
            <a href="{% url 'login' %}" class="btn btn-primary">Iniciar Sesión</a>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        {% if user.role == 'estudiante' %}
        <!-- Botón para crear estudiante -->
        <a href="{% url 'create_estudiante' %}" class="btn btn-primary mb-3 ms-4">Crear Estudiante</a>
        {% endif %}
    {% endif %}
    <ul id="curso-ul">
        {% for estudiante in estudiantes %}
            <li id="curso-li" class="estudiante-item">
                <div class="estudiante-nombre">
                    <a href="{% url 'detail_estudiante' estudiante.id %}">{{ estudiante.nombre }}</a>
                </div>
                <div class="estudiante-email"><a href="mailto:{{ estudiante.email }}">{{ estudiante.email }}</a></div>
            </li>
        {% empty %}
            <li>No hay estudiantes disponibles</li>
        {% endfor %}
    </ul>
{% endblock %}